apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.metadata.name }}
  namespace: {{ .Values.deployment.metadata.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.template.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.template.metadata.labels.app }}
    spec:
      containers:
      {{- range .Values.deployment.template.spec.containers }}
      - name: {{ .name }}
        image: {{ .image }}
        ports:
        - containerPort: {{ .containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .envFrom.configMapRef.name }}
        resources:
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: {{ .resources.limits.memory }}
          requests:
            cpu: {{ .resources.requests.cpu }}
            memory: {{ .resources.requests.memory }}
      {{ end }}
